server:
    port: 8702
spring:
    cloud:      config:        server:          default-application-name: config-server
# 配置git仓库地址          git:            uri: https://github.com/s***w*/myspringcloudconfig
            search-paths: myconfigpath            username: 
            password:         label: master